<div class="login-box">
  <div class="login-logo">
    <a href="<?= $this->url('login') ?>">Biblio<b>Madeira</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <?php if(!empty($this->error)) : ?>
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <?= $this->error; ?>
    </div>
    <?php endif; ?>
    
    <p class="login-box-msg">Preencha seus dados e clique em Entrar</p>

    <form method="post">
      <div class="form-group has-feedback">
        <input name="email" type="email" class="form-control" placeholder="Email" required>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input name="senha" type="password" class="form-control" placeholder="Senha" required>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Entrar</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->