<div class="box box-primary">
    <div class="box-body">
        <?= $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success')); ?>
        <?= $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-error')); ?>
        <?= $this->form()->openTag($form); ?>
          <div class="box-body">
            <div class="form-group">
              <?= $this->formRow($form->get('nome')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('tipo')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('email')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('senha')) ?>
            </div>
          </div>
          
          <!-- /.box-body -->
        
          <div class="box-footer">
            <?= $this->formHidden($form->get('id')) ?>
            <?= $this->formButton($form->get('submit')) ?>
            <a href="<?= $this->url('admin')?>" class="btn btn-default pull-right"><i class="fa fa-close"></i> Cancelar</a>
          </div>
        <?= $this->form()->closeTag(); ?>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->