<div class="box box-primary">
    <div class="box-body">
      <?= $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success')); ?>
      <?= $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-error')); ?>
      <div class="table-responsive">
      <table id="example2" class="table table-bordered table-hover">
        <thead>
        <tr>
          <th>#</th>
          <th>Livro</th>
          <?php if($this->identity()->getIdtipo() < 3): ?>
          <th>Usuário</th>
          <?php endif; ?>
          <th>Data Retirada</th>
          <th>Data Prevista</th>
          <th>Data Devolução</th>
          <th>Valor Empréstimo</th>
          <th>Valor Pago</th>
          <?php if($this->identity()->getIdtipo() < 3): ?>
          <th>Devolver</th>
          <?php endif; ?>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($this->lista as $entity): ?>
                <tr>
                  <td><?php echo $entity->getId(); ?></td>
                  <td><?php echo $entity->getLivro()->getNome(); ?></td>
                  <?php if($this->identity()->getIdtipo() < 3): ?>
                  <td><?php echo $entity->getUsuario()->getNome(); ?></td>
                  <?php endif; ?>
                  <td><?php echo $this->formataData($entity->getDataretirada()); ?></td>
                  <td><?php echo $this->formataData($entity->getDataprevista()); ?></td>
                  <td><?php echo $this->formataData($entity->getDatadevolucao()); ?></td>
                  <td><?php echo $this->formataMoeda($entity->getValoremprestimo()); ?></td>
                  <td><?php echo $this->formataMoeda($entity->getValorpago()); ?></td>
                  <?php if($this->identity()->getIdtipo() < 3): ?>
                  <td>
                      <a href="<?= $this->url('emprestimo', array('action' => 'devolver' , 'id' => $entity->getId())) ?>" class="btn btn-xs btn-success <?=(!empty($entity->getDatadevolucao())) ? 'hidden' : ''?>">
                        <i class="fa fa-check"></i> <span class="hidden-xs">Devolvido</span>
                      </a>
                  </td>
                  <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <th colspan="5">
              <a href="<?= $this->url('emprestimo', array('action' => 'retirar')) ?>" class="btn btn-primary"><i class="fa fa-plus-square-o"></i> Novo Empréstimo</a>
            </th>
        </tr>
        </tfoot>
      </table>
      </div>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->