<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Projeto Biblioteca Madeira') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath('adminlte/dist/css/AdminLTE.min.css'))
                        ->prependStylesheet($this->basePath('adminlte/dist/css/skins/_all-skins.min.css'))
                        ->prependStylesheet($this->basePath('adminlte/bootstrap/css/bootstrap.min.css')) 
                        ->prependStylesheet($this->basePath('css/style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('adminlte/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('adminlte/plugins/jQuery/jquery-2.2.3.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="hold-transition skin-blue fixed sidebar-mini">
        <!-- Site wrapper -->
        <div class="wrapper">
        
          <header class="main-header">
            <!-- Logo -->
            <a href="<?= $this->url('home') ?>" class="logo">
              <!-- mini logo for sidebar mini 50x50 pixels -->
              <span class="logo-mini"><b>BMA</b></span>
              <!-- logo for regular state and mobile devices -->
              <span class="logo-lg">Biblio<b>Madeira</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
              <!-- Sidebar toggle button-->
              <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
        
              <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                  <!-- User Account: style can be found in dropdown.less -->
                  <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <img src="https://www.gravatar.com/avatar/0f5c019f95cb3defc49d0ea8215a15d4?s=160" class="user-image" alt="User Image">
                      <span class="hidden-xs">Fabio Andrei</span>
                    </a>
                    <ul class="dropdown-menu">
                      <!-- User image -->
                      <li class="user-header">
                        <img src="https://www.gravatar.com/avatar/0f5c019f95cb3defc49d0ea8215a15d4?s=160" class="img-circle" alt="User Image">
        
                        <p>
                          Fabio Andrei
                          <small>tifabio@gmail.com</small>
                        </p>
                      </li>
                      <!-- Menu Footer-->
                      <li class="user-footer">
                        <div class="pull-left">
                          <a href="#" class="btn btn-default btn-flat">Perfil</a>
                        </div>
                        <div class="pull-right">
                          <a href="#" class="btn btn-default btn-flat">Sair</a>
                        </div>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>
          </header>
        
          <!-- =============================================== -->
        
          <!-- Left side column. contains the sidebar -->
          <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
              <!-- sidebar menu: : style can be found in sidebar.less -->
              <ul class="sidebar-menu">
                <li><a href="#"><i class="fa fa-users"></i> <span>Usuários</span></a></li>
                <li><a href="#"><i class="fa fa-vcard"></i> <span>Locatários</span></a></li>
                <li><a href="#"><i class="fa fa-list-ul"></i> <span>Categoria de livros</span></a></li>
                <li><a href="#"><i class="fa fa-book"></i> <span>Livros</span></a></li>
                <li><a href="#"><i class="fa fa-calendar"></i> <span>Empréstimos</span></a></li>
            </section>
            <!-- /.sidebar -->
          </aside>
        
          <!-- =============================================== -->
        
          <!-- Content Wrapper. Contains page content -->
          <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
              <h1>Dashboard</h1>
            </section>
        
            <!-- Main content -->
            <section class="content">
              <?= $this->content ?>
            </section>
            <!-- /.content -->
          </div>
          <!-- /.content-wrapper -->
        
          <footer class="main-footer">
            <strong>Github source: <a href="https://github.com/tifabio/testemadeira" target="_blank">tifabio/testemadeira</a></strong>
          </footer>
        
        </div>
        <!-- ./wrapper -->
        <?php echo $this->inlineScript()->prependFile($this->basePath('adminlte/dist/js/app.min.js'))
                                        ->prependFile($this->basePath('adminlte/plugins/slimScroll/jquery.slimscroll.min.js'))
                                        ->prependFile($this->basePath('adminlte/plugins/fastclick/fastclick.js')); ?>
    </body>
</html>
