<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Projeto Biblioteca Madeira') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath('adminlte/dist/css/AdminLTE.min.css'))
                        ->prependStylesheet($this->basePath('adminlte/dist/css/skins/_all-skins.min.css'))
                        ->prependStylesheet($this->basePath('adminlte/bootstrap/css/bootstrap.min.css')) 
                        ->prependStylesheet($this->basePath('css/style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('adminlte/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('adminlte/plugins/jQuery/jquery-2.2.3.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="hold-transition login-page">
        
        <?= $this->content ?>
        
    </body>
</html>
