<div class="box box-primary">
    <div class="box-body">
        <?= $this->form()->openTag($form); ?>
          <div class="box-body">
            <div class="form-group">
              <?= $this->formRow($form->get('nome')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('cpf')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('datanascimento')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('email')) ?>
            </div>
            <div class="form-group">
              <?= $this->formRow($form->get('senha')) ?>
            </div>
          </div>
          
          <!-- /.box-body -->
        
          <div class="box-footer">
            <?= $this->formHidden($form->get('tipo')) ?>
            <?= $this->formHidden($form->get('id')) ?>
            <?= $this->formButton($form->get('submit')) ?>
            <a href="<?= $this->url('locatario')?>" class="btn btn-default pull-right"><i class="fa fa-close"></i> Cancelar</a>
          </div>
        <?= $this->form()->closeTag(); ?>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->

<script>
  $(function () {
    $("#cpf").inputmask("999.999.999-99");
    $("form").submit(function() {
      $("#cpf").inputmask('remove');
    });
    $('#datanascimento').datepicker({
      autoclose: true,
      format: 'dd/mm/yyyy'
    });
  });
</script>