<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="fa fa-book"></i></span>
    
        <div class="info-box-content">
          <span class="info-box-text">Livros cadastrados</span>
          <span class="info-box-number"><?= $this->dashboard['cadastrados'] ?></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-green"><i class="fa fa-book"></i></span>
    
        <div class="info-box-content">
          <span class="info-box-text">Livros emprestados</span>
          <span class="info-box-number"><?= $this->dashboard['emprestados'] ?></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    
    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>
    
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-red"><i class="fa fa-book"></i></span>
    
        <div class="info-box-content">
          <span class="info-box-text">Livros atrasados</span>
          <span class="info-box-number"><?= $this->dashboard['atrasados'] ?></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-dollar"></i></span>
    
        <div class="info-box-content">
          <span class="info-box-text"><b>Faturamento</b></span>
          <span class="info-box-text"><b><?=date('Y/m', strtotime("-1 month"))?></b>: <?=$this->formataMoeda($this->dashboard['faturamento'][date('Y/m', strtotime("-1 month"))])?></span>
          <span class="info-box-text"><b><?=date('Y/m')?>:</b> <?=$this->formataMoeda($this->dashboard['faturamento'][date('Y/m')])?></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
</div>